# Build settings
title: The Real – A Daytime Talk Show with co-hosts Adrienne Houghton, Loni Love, Jeannie Mai Jenkins and Garcelle Beauvais. | TheReal.com
description: The Real is an hour-long, five-days-a-week, talk-variety show.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme